### ISSUE TITLE
RNA-seq results

### ISSUE THREAD

**Issue by BenxiaHu** [nottalexi/brain-cell-type-peak-files#1]
Hello,
    Based on your science paper entitled "Brain cell type–specific enhancer–promoter interactome maps and disease risk association", you also performed RNA-seq in neurons/astrocytes/micorglia/oligodendrocytes. Would you like to upload normalized expression matrices of those RNA-seq?

**Comment by nottalexi** [comment]
Hi, I have uploaded normalized expression matrices for the RNA-seq experiment in the 2019 Science paper. These have been uploaded as 2 files, one with TPM values and the other with DESeq2 Rlog values. These are located in /brain-cell-type-peak-files. I can also provide a link to the original fastq files if you need them. Best, Alexi

**Comment by BenxiaHu** [comment]
many thanks. Alexi
it seems that the normalized expression matrices you unloaded are related to BIN1 deletion.
What I want is this expression matrices (fig2 B):
![image](https://user-images.githubusercontent.com/12387462/118408218-98ad4d80-b652-11eb-97ac-eee25c3ce066.png)

I can also provide a link to the original fastq files if you need them---yes, please provide the link to the original fastq files to me.
Best,

**Comment by nottalexi** [comment]
Hi, apologies for the confusion. Inge Holtman may have the normalized count matrices you are requesting for the histone marks, it may be best to contact her directly. 
Unfortunately, I cannot give you a direct link for the fastq files for the ChIP-seq data as this was generated using human resected tissue and therefore access is somewhat restricted. You would have to apply for access to these files through dbGap here: https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001373.v2.p2

**Comment by BenxiaHu** [comment]
okay. thanks a lot.
